export const ADD_INGREDIENTS = "ADD_INGREDIENTS";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const CLEAR_STATE = "CLEAR_STATE";

export const GET_ORDERS = "GET_ORDERS";
export const GET_ORDERS_START = "GET_ORDERS_START";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";

export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNIN = "SIGNIN";
export const SIGNIN_ERROR = "SIGNUP_ERROR";
export const ON_SIGN_METHOD_CHANGE = "ON_SIGN_METHOD_CHANGE";
export const LOGOUT = "LOGOUT";
export const GET_LOCAL_TOKEN = "GET_LOCAL_TOKEN";
